IMG_CENTER = 320

#Lookahead points
LOOKAHEAD_POINTS_Y = [200, 320, 380]
LOOKAHEAD_POINTS_WEIGHTS = [0.2, 0.3, 0.5]

#Steering angle
SERVO_CENTER = 0
MAX_STEERING_ANGLE = 30.0
MIN_STEERING_ANGLE = 30.0
STEERING_GAIN = 0.12

#Curvature radius
STRAIGHT_RADIUS = 4000
CURVE_RADIUS = 1500
SHARP_CURVE_RADIUS = 700

#Speed (PWMW duty cycle)
MAX_SPEED = 40
NORMAL_SPEED = 30
LOW_SPEED = 20

#Deadband
OFFSET_DEADBAND = 5

#Lane change offset 
LANE_CHANGE_OFFSET = 200

#EMA smoothing for steering
STEERING_EMA_ALPHA = 0.3

